# Generated by Django 4.2.2 on 2023-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/', verbose_name='User_profile_pic'),
        ),
    ]
